name: sea-turtle-app
services:
  - name: web
    git:
      repo_clone_url: https://github.com/yourusername/your-repo.git
    env: python
    buildpacks:
      - url: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
      - url: heroku/python
    run_command: python application.py
