name: sea-turtle-app
services:
  - name: web
    git:
      repo_clone_url: https://github.com/K-Irwin8/digitalocean.git
    env: python
    buildpacks:
      - url: heroku/python
    build_command: |
      # Download and extract the static FFmpeg binary
      wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
      tar -xf ffmpeg-release-amd64-static.tar.xz
      # Move the FFmpeg binary to ./bin
      mkdir -p bin
      cp ffmpeg-*-amd64-static/ffmpeg bin/
      chmod +x bin/ffmpeg
      # Install Python dependencies
      pip install -r requirements.txt
    run_command: python application.py
